### ISSUE TITLE
After playing a single game, I must restart the game to play another match

### ISSUE THREAD

**Issue by PossibleReference** [RealProHenis/ButterflyLauncher#14]
Have no idea why this happens. Chapter 2+ just returns to the lobby

**Comment by RealProHenis** [comment]
I'm a little confused what you mean. Are you saying that you can't return to the lobby when you're in-game on any Chapter 2 versions? Do you see a return to lobby button? Does the button not work?

**Comment by PossibleReference** [comment]
No, it's that after one match, authentication breaks making you not able to queue

**Comment by RealProHenis** [comment]
Ahhh, are you talking about when you launch Singleplayer? If so, you're correct. You do need to restart your game after you leave match of singleplayer. The reason for this is because the singleplayer game that you connect to is actually just a modified version of a Project Reboot game server that's silently running in the background of your computer. After you leave a singleplayer match, you'd have to restart the singleplayer game server & wait for it to finish loading before trying to join again. When you launch Singleplayer, a silent background game server is started before the actual Fortnite game. In order to not have to restart the game, I'd have to find a way to kill the game server process after you leave, and then let the user know to not press the Play button until a singleplayer game server is finished launching, and I'm not sure the best way to do that. In most cases, I assume that if a user leaves a singleplayer match, they're done with singleplayer.
